### ISSUE TITLE
[DOCUMENTATION] - TODO following July 8 Meeting with Oran

### ISSUE THREAD

**Issue by ShawnLemuelDabi** [ShawnLemuelDabi/ITP-Group-18#16]
- [x] Create the survey
- [ ] Find references for all health information (This will be carried forward in the next sprint)
- [x] Future Consequence Figma Screen
- [x] Adjust text in screens to be more kid-friendly
