### ISSUE TITLE
[DOCUMENTATION] - Refine the current application based on Professor Feedback 19 July 2022

### ISSUE THREAD

**Issue by ShawnLemuelDabi** [ShawnLemuelDabi/ITP-Group-18#17]
- [x] Amend the survey questions as discussed (Linked to #18 )
- [x] Communicate that eating one fatty food will not cause instant fatness (Linked to #19 ) Brainstorm more, a better child-friendly way to communicate the message
- [x] Update NTUC on what was discussed in 19 July 2022 Meeting with professors (Linked to #22 )

**Comment by asifexplore** [comment]
Things that the team has taken notes on during the meeting with Professor Dan and Professor Oran. 

Things to continue improving or consider for the figma
1. Avocado changes are not visible enough (Esp Unhealthy ones) 
2. Communicate that eating one fatty food not gonna make "me" fat
3. Prof Dan still can't catch the flow of the application
4. Make things more visually like animations? 
5. Communicating the right message, the purpose of the app
6. Sequential Gif => Flow, Gamification, and End Goals 
7. Require Translation? E.g. Chinese, Malay, & Tamil

Advice Given for Presentation
1. Don't keep more than 10 slides for 15 min presentation with including Animations 
2. Animations first then present slides. (Able to track and pace time during presentation) 
3. Don't put too much content inside the slides. 
4. Target for clean slides with not much design.

**Comment by ShawnLemuelDabi** [comment]
Shifted to sprint 10

**Comment by ShawnLemuelDabi** [comment]
Shifted to sprint 11
